services:
  super-xampp:
    build: .
    image: dnoi/super-xampp:1.0.0    
    container_name: super_xampp
    restart: always
    ports:
      - "80:80"
      - "3306:3306"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - A:/Desenvolvimento/Docker/xampp_server/mysql_data:/var/lib/mysql

volumes:
  mysql_data: